"""Train the digit classifier, quantize to int8, and export it for the firmware.

Usage:
    uv run python train.py                         # synthetic data only
    uv run python train.py --real ../data/real     # plus real crops in <dir>/<class>/*.png
"""
import argparse
from pathlib import Path

import cv2
import numpy as np
import tensorflow as tf

import synth
from common import CLASSES, IMG_H, IMG_W, normalize

ROOT = Path(__file__).resolve().parent
FIRMWARE_MODEL = ROOT.parent / "firmware" / "main" / "model_data.cc"


def build_model():
    def block(x, filters):
        x = tf.keras.layers.Conv2D(filters, 3, padding="same", use_bias=False)(x)
        x = tf.keras.layers.BatchNormalization()(x)
        x = tf.keras.layers.ReLU()(x)
        return tf.keras.layers.MaxPooling2D()(x)

    inp = tf.keras.Input((IMG_H, IMG_W, 1))
    x = block(inp, 16)
    x = block(x, 32)
    x = block(x, 32)
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(64, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    out = tf.keras.layers.Dense(len(CLASSES), activation="softmax")(x)
    return tf.keras.Model(inp, out)


def load_real(root):
    images, labels = [], []
    for idx, name in enumerate(CLASSES):
        for path in sorted((Path(root) / name).glob("*.png")):
            img = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
            if img is None:
                continue
            # Crops from the device are already normalized; this is a no-op for them.
            images.append(normalize(img))
            labels.append(idx)
    if not images:
        return np.zeros((0, IMG_H, IMG_W), np.uint8), np.zeros(0, np.int64)
    return np.stack(images), np.array(labels, np.int64)


def to_float(images):
    return images[..., None].astype(np.float32) / 255.0


def export_int8(model, calib, out_dir):
    # Going through a SavedModel freezes Keras 3 variables; converting a live
    # tf.function leaves READ_VARIABLE ops that break calibration.
    saved = out_dir / "saved_model"
    # Fixed batch of 1 so Flatten becomes a plain RESHAPE, without SHAPE/STRIDED_SLICE/PACK.
    model.export(str(saved), format="tf_saved_model", verbose=False,
                 input_signature=[tf.TensorSpec([1, IMG_H, IMG_W, 1], tf.float32)])
    converter = tf.lite.TFLiteConverter.from_saved_model(str(saved))
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: ([calib[i:i + 1]] for i in range(len(calib)))
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite = converter.convert()
    (out_dir / "model_int8.tflite").write_bytes(tflite)
    return tflite


def eval_tflite(tflite, images, labels):
    interp = tf.lite.Interpreter(model_content=tflite)
    interp.allocate_tensors()
    inp, out = interp.get_input_details()[0], interp.get_output_details()[0]
    in_scale, in_zp = inp["quantization"]
    preds = np.empty(len(images), np.int64)
    for i, img in enumerate(images):
        q = np.round(img.astype(np.float32) / 255.0 / in_scale + in_zp)
        interp.set_tensor(inp["index"], np.clip(q, -128, 127).astype(np.int8)[None, ..., None])
        interp.invoke()
        preds[i] = np.argmax(interp.get_tensor(out["index"])[0])
    return preds


def report(name, preds, labels):
    acc = float(np.mean(preds == labels)) if len(labels) else float("nan")
    print(f"{name}: accuracy {acc:.4f} on {len(labels)} crops")
    for c in range(len(CLASSES)):
        mask = labels == c
        if mask.any():
            wrong = preds[mask] != c
            if wrong.any():
                confused = np.bincount(preds[mask][wrong], minlength=len(CLASSES))
                top = ", ".join(f"{CLASSES[k]}x{v}" for k, v in enumerate(confused) if v)
                print(f"  {CLASSES[c]:>6}: {wrong.sum()}/{mask.sum()} wrong ({top})")


def write_c_array(tflite, path):
    rows = [", ".join(f"0x{b:02x}" for b in tflite[i:i + 16]) for i in range(0, len(tflite), 16)]
    body = ",\n  ".join(rows)
    path.write_text(
        "// Generated by training/train.py. Do not edit.\n"
        '#include "model_data.h"\n\n'
        f"alignas(16) const unsigned char g_model_data[] = {{\n  {body}\n}};\n"
        f"const unsigned int g_model_data_len = {len(tflite)};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--synth", type=int, default=60000)
    ap.add_argument("--real", default=str(ROOT.parent / "data" / "real"))
    ap.add_argument("--real-repeat", type=int, default=10,
                    help="oversample real crops so they are not drowned by synthetic ones")
    ap.add_argument("--epochs", type=int, default=25)
    ap.add_argument("--out", default=str(ROOT / "out"))
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--export-only", action="store_true",
                    help="skip training; quantize and export <out>/model.keras")
    args = ap.parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.export_only:
        args.synth = min(args.synth, 5000)
    print(f"generating {args.synth} synthetic crops...")
    sx, sy = synth.generate(args.synth, seed=args.seed)
    vx, vy = synth.generate(args.synth // 10, seed=args.seed + 1)

    rx, ry = load_real(args.real)
    rng = np.random.default_rng(args.seed)
    order = rng.permutation(len(rx))
    split = int(len(rx) * 0.8)
    rtx, rty = rx[order[:split]], ry[order[:split]]
    rvx, rvy = rx[order[split:]], ry[order[split:]]
    print(f"real crops: {len(rtx)} train, {len(rvx)} val")

    tx = np.concatenate([sx] + [rtx] * args.real_repeat)
    ty = np.concatenate([sy] + [rty] * args.real_repeat)

    if args.export_only:
        model = tf.keras.models.load_model(out_dir / "model.keras")
    else:
        model = build_model()
        model.summary()
        model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                      loss="sparse_categorical_crossentropy", metrics=["accuracy"])
        model.fit(
            to_float(tx), ty, batch_size=128, epochs=args.epochs, shuffle=True,
            validation_data=(to_float(vx), vy),
            callbacks=[
                tf.keras.callbacks.ReduceLROnPlateau(patience=3, factor=0.5),
                tf.keras.callbacks.EarlyStopping(patience=6, restore_best_weights=True),
            ],
            verbose=2)
        model.save(out_dir / "model.keras")

    calib = to_float(tx[rng.permutation(len(tx))[:500]])
    tflite = export_int8(model, calib, out_dir)
    print(f"int8 model: {len(tflite)} bytes")

    report("synthetic val (int8)", eval_tflite(tflite, vx, vy), vy)
    if len(rvx):
        report("real val (int8)", eval_tflite(tflite, rvx, rvy), rvy)

    write_c_array(tflite, FIRMWARE_MODEL)
    print(f"wrote {FIRMWARE_MODEL}")


if __name__ == "__main__":
    main()
